# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: Restore Nuget Packages
        run: nuget restore SmartVote.sln
      - name: Build
        run: |
          dotnet build $Env:GITHUB_WORKSPACE\lib\FFXIVClientStructs\FFXIVClientStructs.sln /p:Configuration=Release /p:DefineConstants=XL_NOAUTOUPDATE
          dotnet build $Env:GITHUB_WORKSPACE\lib\ClickLib\ClickLib.sln /p:Configuration=Release /p:DefineConstants=XL_NOAUTOUPDATE
          dotnet build $Env:GITHUB_WORKSPACE\SmartVote.sln /p:Configuration=Release /p:DefineConstants=XL_NOAUTOUPDATE
      #- name: Protect
      #  run: |
      #    cd "$Env:GITHUB_WORKSPACE"
      #    .\Lib\.NET_Reactor\dotNET_Reactor.Console.exe -file ".\SmartVote\bin\Release\net5.0-windows\SmartVote.dll" -antitamp 1 -hide_calls 1 -control_flow_obfuscation 1 -flow_level 9 -resourceencryption 1
      #    Move-Item -Path .\SmartVote\bin\Release\net5.0-windows\SmartVote_Secure\* -Destination .\SmartVote\bin\Release\net5.0 -Force
      #    Remove-Item -Path .\SmartVote\bin\Release\net5.0-windows\SmartVote_Secure -Force -Recurse
      #    Remove-Item -Path .\SmartVote\bin\Release\net5.0-windows\SmartVote -Force -Recurse
      #    Remove-Item -Path .\SmartVote\bin\Release\net5.0-windows\ref -Force -Recurse
      #    Remove-Item -Path .\SmartVote\bin\Release\net5.0-windows\SmartVote.deps.json -Force -Recurse
      #    mkdir -Path .\SmartVote\bin\Package\
      - name: CleanUp
        run: |
          cd "$Env:GITHUB_WORKSPACE"
          Remove-Item -Path .\SmartVote\bin\Release\net5.0-windows\SmartVote -Force -Recurse
          Remove-Item -Path .\SmartVote\bin\Release\net5.0-windows\ref -Force -Recurse
          Remove-Item -Path .\SmartVote\bin\Release\net5.0-windows\SmartVote.deps.json -Force -Recurse
          mkdir -Path .\SmartVote\bin\Package\
      - name: Package
        uses: papeloto/action-zip@v1
        with:
          files: SmartVote\bin\Release\net5.0-windows\SmartVote.dll SmartVote\bin\Release\net5.0-windows\SmartVote.json SmartVote\bin\Release\net5.0-windows\SmartVote.pdb
          dest: SmartVote\bin\Package\latest.zip
      - name: Package
        run: |
          cd "$Env:GITHUB_WORKSPACE"
          Copy-Item -Path .\SmartVote\bin\Release\net5.0-windows\SmartVote.json -Destination .\SmartVote\bin\Package\
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SmartVote
          path: ${{ github.workspace }}\SmartVote\bin\Release\net5.0-windows
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: ${{ github.workspace }}\SmartVote\bin\Package\
